
dist: trusty
sudo: false
language: node_js

node_js: "8"

cache: yarn

env:
  - NODE_ENV=development

install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH="$HOME/.yarn/bin:$PATH"
  - cd server && yarn

script:
  - yarn run test
